---
title: "About"
---

## Background
Before joining the Masters of Data Science Program (2026-2027), I worked as a Data Analyst and Developer at DarkVision Technologies. 
My role involved data cleaning, measuring, analysis, manipulation and processing into various deliverables in forms of Excel, Word Documents, and plots.
The main languages I interacted with during these two roles were Matlab and Python, and the occasional SQL code. 

## Why Data Science
In the 3 years at DarkVision, I was focused on honing my practical skills on using various Python functionalities to manipulate and process data. 
Although practical skills are useful, I felt like I was lacking in the theoretical knowledge and the "why" in some design decisions the team made for 
certain initiatives. Returning back to school for Data Science felt like the right move to take a step back and revisit concepts that I may be 
familiar with applying, so that it is strengthened with the theories behind them. 

## Outside of Data Science
Outside of Data Science, I love music, photography, and nature.
Some music genre's I am a fan of include (but are not limited to) indie-folk, alternative-pop, and punk-pop music.
I have a photography account on instagram with the user handle [@cnada.jpg](https://www.instagram.com/cnada.jpg?stkn=MTJ5am9nazl6djRwdA%3D%3D&utm_source=qr), where I share my photos of people and nature adventures!

